name: "Build components' Docker images"

on:
  workflow_run:
    workflows: [Build base Docker image]
    types:
      - completed
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./services/meta.sr.ht
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/srht-meta:latest
  git:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./services/git.sr.ht
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/srht-git:latest
