name: "Build the Docker images"

on:
  push:
    paths:
      - 'base/Dockerfile'
  schedule:
    - cron: '0 0 */7 * *' # runs weekly
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v3
        with:
          push: true
